from sqlmodel import SQLModel, Field
from typing import Optional

# This class defines the Database Table structure using SQLModel
class Task(SQLModel, table=True):
    # Primary key for the table, automatically generated by the database
    id: Optional[int] = Field(default=None, primary_key=True)
    
    # Required field for the task title
    title: str
    
    # Optional field for a detailed description of the task
    description: Optional[str] = None
    
    # Boolean field to track status, defaults to False (Not Completed)
    is_completed: bool = Field(default=False)