from pydantic import BaseModel
from typing import Optional

# This schema is used when creating a new task. 
# It requires a title but makes the description optional.
class TaskCreate(BaseModel):
    title: str
    description: Optional[str] = None

# This schema is used for returning data to the user.
# It includes the 'id' generated by the database and the 'is_completed' status.
class TaskRead(BaseModel):
    id: int
    title: str
    description: Optional[str] = None
    is_completed: bool

# This schema is used for updating existing tasks.
# All fields are optional to allow partial updates (PATCH).
class TaskUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    is_completed: Optional[bool] = None